In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [60]:
df_fake = pd.read_csv("./data/Fake.csv")
df_true = pd.read_csv("./data/True.csv")
df_true

title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
...                                                  ...           ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...     worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...     worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...     worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...     worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...     worldnews   

                     date  
0      December 31, 2017   
1      December 29, 2017   
2      December 31, 2017   
3      December 30, 2017   
4      December 29, 2017   
...                   ...  
21412    August 22, 2017   
21413    August 22, 2017   
21414    August 22, 2017   
21415    August 22, 2017   
21416    August 22, 2017   

[21417 rows x 4 columns]

In [67]:
a = df_true.head(10)
def remove_city_reuters(text):
    text = re.sub(r'^\w+\s+\((Reuters)\)\s+-\s+', '',text)

df_true['text'] = df_true['text'].str.replace(r'^.*\(Reuters\)\s*-\s*', '', regex=True)
df_true

title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject  \
0      The head of a conservative Republican faction ...  politicsNews   
1      Transgender people will be allowed for the fir...  politicsNews   
2      The special counsel investigation of links bet...  politicsNews   
3      Trump campaign adviser George Papadopoulos tol...  politicsNews   
4      President Donald Trump called on the U.S. Post...  politicsNews   
...                                                  ...           ...   
21412  NATO allies on Tuesday welcomed President Dona...     worldnews   
21413  LexisNexis, a provider of legal, regulatory an...     worldnews   
21414  In the shadow of disused Soviet-era factories ...     worldnews   
21415  Vatican Secretary of State Cardinal Pietro Par...     worldnews   
21416  Indonesia will buy 11 Sukhoi fighter jets wort...     worldnews   

                     date  
0      December 31, 2017   
1      December 29, 2017   
2      December 31, 2017   
3      December 30, 2017   
4      December 29, 2017   
...                   ...  
21412    August 22, 2017   
21413    August 22, 2017   
21414    August 22, 2017   
21415    August 22, 2017   
21416    August 22, 2017   

[21417 rows x 4 columns]

In [3]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [68]:
df_fake["class"] = 0
df_true["class"] = 1

In [69]:
df_fake.shape, df_true.shape    

((23481, 5), (21417, 5))

In [70]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0

In [71]:
# Removing last 10 rows for manual testing
df_fake_manual_testing = df_fake.tail(10)
for i in range(23480,23470,-1):
    df_fake.drop([i], axis = 0, inplace = True)
    
    
df_true_manual_testing = df_true.tail(10)
for i in range(21416,21406,-1):
    df_true.drop([i], axis = 0, inplace = True)

In [72]:
df_fake.shape, df_true.shape

((23471, 5), (21407, 5))

In [73]:
df_fake_manual_testing["class"] = 0
df_true_manual_testing["class"] = 1

C:\Users\felli\AppData\Local\Temp\ipykernel_21324\860779283.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fake_manual_testing["class"] = 0
C:\Users\felli\AppData\Local\Temp\ipykernel_21324\860779283.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_true_manual_testing["class"] = 1


In [74]:
df_fake_manual_testing.head(10)

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east   
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0  
23476  January 16, 2016      0  
23477  January 16, 2016      0  
23478  January 15, 2016      0  
23479  January 14, 2016      0  
23480  January 12, 2016      0

In [75]:
df_manual_testing = pd.concat([df_fake_manual_testing,df_true_manual_testing], axis = 0)
df_manual_testing.to_csv("./data/manual_testing.csv")

In [76]:
df_merge = pd.concat([df_fake, df_true], axis =0 )
df_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [77]:
df = df_merge.drop(["title", "subject","date"], axis = 1)

In [78]:
df = df.sample(frac = 1)

In [79]:
df.head()

text  class
12333                                              Ouch!      0
20109  The Russian Navy on Thursday fired seven cruis...      1
16488             FIVE FACTS ABOUT HILLARY AND BENGHAZI:      0
5293   President Donald Trump said on Thursday he wan...      1
6669   President-elect Donald Trump said on Thursday ...      1

In [80]:
df.reset_index(inplace = True)
df.drop(["index"], axis = 1, inplace = True)

In [81]:
df.columns

Index(['text', 'class'], dtype='object')

In [82]:
df.head()

text  class
0                                              Ouch!      0
1  The Russian Navy on Thursday fired seven cruis...      1
2             FIVE FACTS ABOUT HILLARY AND BENGHAZI:      0
3  President Donald Trump said on Thursday he wan...      1
4  President-elect Donald Trump said on Thursday ...      1

In [83]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [84]:
df["text"] = df["text"].apply(wordopt)

In [85]:
x = df["text"]
y = df["class"]

In [86]:
x

0                                                    ouch 
1        the russian navy on thursday fired seven cruis...
2                   five facts about hillary and benghazi 
3        president donald trump said on thursday he wan...
4        president elect donald trump said on thursday ...
                               ...                        
44873    republicans are working overtime trying to sel...
44874                              spread this everywhere 
44875    it clear that common sense isn t what these he...
44876    china s ruling communist party on wednesday un...
44877    new york s attorney general  who has filed a l...
Name: text, Length: 44878, dtype: object

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.98)

In [129]:
x_train.shape, x_test.shape

((2243,), (42635,))

In [130]:
x_train

23173    last saturday  donald trump woke at the crack ...
20642    the anti nuclear group which won the  nobel pe...
34513    the u s  senate voted overwhelmingly on wednes...
34876    i forgot about the claim from hillary clinton ...
41465    there is no reason to suspect that two bags of...
                               ...                        
31159    ever since former house speaker john boehner a...
28104    summer snow is coming to alaska just in time f...
22681    capitalism is a crazy system  on black friday ...
2463     divisions have emerged among advisers to presi...
3191     donald trump s support has surged and he is no...
Name: text, Length: 2243, dtype: object

In [131]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [132]:
from sklearn.linear_model import LogisticRegression


LR_new = LogisticRegression()
LR_new.fit(xv_train, y_train)

LogisticRegression()

In [133]:
LR_new.score(xv_test, y_test)
pred_lr=LR_new.predict(xv_test)
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.96      0.95      0.96     22289
           1       0.95      0.96      0.96     20346

    accuracy                           0.96     42635
   macro avg       0.96      0.96      0.96     42635
weighted avg       0.96      0.96      0.96     42635



In [134]:
df_manual_testing["text"] = df_manual_testing["text"].apply(wordopt)
x_manual_test = df_manual_testing["text"]

In [135]:
x_manual_test_vect = vectorization.transform(x_manual_test)
pred_LR = LR_new.predict(x_manual_test_vect)
pred_LR

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [119]:
manual_input = ["Donald Trump is the new elected president of USA in 2016."]
manual_input = vectorization.transform(manual_input)
pred = LR_new.predict(manual_input)
pred

array([0])

In [ ]:
from sentence_transformers import SentenceTransformer

# Carrega um modelo pré-treinado de embeddings multilíngue
model_name = 'paraphrase-MiniLM-L3-v2'
model = SentenceTransformer(model_name)

model


c:\ITA\exame-cmc16\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [26]:
model.encode("oi")

array([-5.99944234e-01, -2.77464688e-01,  2.73908943e-01, -1.51368290e-01,
       -5.87941885e-01,  1.92995876e-01,  7.25866437e-01, -1.94113225e-01,
       -1.87129349e-01, -5.10930836e-01,  4.18616503e-01, -1.70675784e-01,
       -1.06233567e-01, -5.57525903e-02, -2.15937376e-01,  1.56460941e-01,
       -2.04897270e-01, -4.03120294e-02, -4.73357052e-01,  5.45612752e-01,
       -5.98393679e-02,  1.09740004e-01,  5.73980995e-02, -2.08903611e-01,
        2.79017985e-01, -2.55055308e-01,  3.54012758e-01,  2.81007737e-01,
        4.48253274e-01, -5.36020339e-01,  2.33343124e-01, -1.03401855e-01,
        7.50664413e-01,  1.00687891e-01,  5.82742020e-02, -4.85176519e-02,
        4.04831737e-01, -2.92639434e-01, -4.73688960e-01,  3.11557561e-01,
        4.37124580e-01,  1.61754817e-01,  2.49128908e-01,  1.94518939e-02,
        1.68326050e-01, -1.46074429e-01,  1.17201254e-01,  5.77517822e-02,
       -4.16121215e-01, -3.47058713e-01,  5.35824656e-01,  1.02702305e-01,
       -8.76374841e-01,  

In [25]:
xv_train_10 = model.encode(x_train[:10])

KeyError: np.int64(4)

In [46]:
xv_train_10.shape

(10, 384)

In [27]:
# Gera os embeddings para os conjuntos de treinamento e teste
xv_train = x_train.apply(lambda x: model.encode(x))

In [28]:
np.save('./data/xv_train.npy', xv_train)

In [30]:
xv_test = x_test.apply(lambda x: model.encode(x))

In [31]:
np.save('./data/xv_test.npy', xv_test)

In [37]:
xv_train_array = np.array(xv_train.tolist())
xv_train_array

array([[ 0.07299594, -0.02148917,  0.0197097 , ..., -0.17377743,
         0.22982885, -0.10851801],
       [-0.10912595, -0.05322869, -0.03921903, ..., -0.0627545 ,
        -0.01937047, -0.09655197],
       [-0.04869758,  0.04737613,  0.01339676, ...,  0.06214176,
         0.0144489 , -0.0892719 ],
       ...,
       [-0.08564429,  0.01940118, -0.04078446, ..., -0.01652716,
         0.19667642,  0.0755534 ],
       [-0.10372493, -0.2787671 ,  0.02854047, ...,  0.20312093,
         0.06556848,  0.08138904],
       [ 0.00262731,  0.2334014 , -0.07559916, ...,  0.12826422,
        -0.20990293, -0.0094826 ]], dtype=float32)

In [38]:

from sklearn.linear_model import LogisticRegression

# Convert xv_train to a 2D numpy array

LR = LogisticRegression()
LR.fit(xv_train_array, y_train)

LogisticRegression()

In [40]:
# Predict probabilities
xv_test_array = np.array(xv_test.tolist())
y_pred_prob = LR.predict_proba(xv_test_array)[:, 1]

# Define a dynamic threshold
# threshold = 0.5  # You can adjust this threshold based on your requirements

# Apply the threshold to get the final predictions
# y_pred = (y_pred_prob >= threshold).astype(int)
y_pred_prob

array([9.91865889e-01, 9.94730209e-01, 9.62712409e-01, ...,
       6.81160290e-05, 5.50271371e-04, 9.91891274e-01])

In [43]:
pred_lr=LR.predict(xv_test_array)

In [41]:
LR.score(xv_test_array, y_test)

0.974777183600713

In [44]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      5846
           1       0.97      0.98      0.97      5374

    accuracy                           0.97     11220
   macro avg       0.97      0.97      0.97     11220
weighted avg       0.97      0.97      0.97     11220



In [94]:
df_manual_testing["text"] = df_manual_testing["text"].apply(wordopt)

In [ ]:
input_raw = df_manual_testing["text"]
input_test = model.encode("")

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   
21407  Mata Pires, owner of embattled Brazil builder ...   
21408  U.S., North Korea clash at U.N. forum over nuc...   
21409  U.S., North Korea clash at U.N. arms forum on ...   
21410  Headless torso could belong to submarine journ...   
21411  North Korea shipments to Syria chemical arms a...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text      subject  \
23471   century wire says this week  the historic int...  Middle-east   
23472   by dady chery and gilbert mercierall writers ...  Middle-east   
23473  vic bishop waking timesour reality is carefull...  Middle-east   
23474  paul craig robertsin the last years of the  ce...  Middle-east   
23475  robert fantina counterpunchalthough the united...  Middle-east   
23476   century wire says as  reported earlier this w...  Middle-east   
23477   century wire says it s a familiar theme  when...  Middle-east   
23478  patrick henningsen   century wireremember when...  Middle-east   
23479   century wire says al jazeera america will go ...  Middle-east   
23480   century wire says as  predicted in its new ye...  Middle-east   
21407  sao paulo  reuters    cesar mata pires  the ow...    worldnews   
21408  geneva  reuters    north korea and the united ...    worldnews   
21409  geneva  reuters    north korea and the united ...    worldnews   
21410  copenhagen  reuters    danish police said on t...    worldnews   
21411  united nations  reuters    two north korean sh...    worldnews   
21412  brussels  reuters    nato allies on tuesday we...    worldnews   
21413  london  reuters    lexisnexis  a provider of l...    worldnews   
21414  minsk  reuters    in the shadow of disused sov...    worldnews   
21415  moscow  reuters    vatican secretary of state ...    worldnews   
21416  jakarta  reuters    indonesia will buy  sukhoi...    worldnews   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0  
23476  January 16, 2016      0  
23477  January 16, 2016      0  
23478  January 15, 2016      0  
23479  January 14, 2016      0  
23480  January 12, 2016      0  
21407  August 22, 2017       1  
21408  August 22, 2017       1  
21409  August 22, 2017       1  
21410  August 22, 2017       1  
21411  August 21, 2017       1  
21412  August 22, 2017       1  
21413  August 22, 2017       1  
21414  August 22, 2017       1  
21415  August 22, 2017       1  
21416  August 22, 2017       1

In [45]:
x_manual_test = df_manual_testing["text"]
x_manual_test.shape

(20,)

In [47]:

x_manual_test_encoded = x_manual_test.apply(lambda x: model.encode(x))
x_manual_test_encoded_array = np.array(x_manual_test_encoded.tolist())

In [48]:
LR.predict(x_manual_test_encoded_array)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [51]:
df

text  class
0      is there a single person left on robert muelle...      0
1      donald trump already has blood on his hands  o...      0
2      the following statements were posted to the ve...      1
3      from tmzivanka trump just had a bumpy start to...      0
4      washington  reuters    the obama administratio...      1
...                                                  ...    ...
44873  riyadh  reuters    the failed north korean mis...      1
44874  this is what being pathetic looks like house s...      0
44875  washington  reuters    u s  transportation sec...      1
44876  san juan  puerto rico  reuters    u s  preside...      1
44877  oh  alabama  in some ways  you ve replaced ari...      0

[44878 rows x 2 columns]